spring:
  datasource:
    url: jdbc:mysql://123.57.241.113:3306/db_flash_sale?useUnicode=true&serverTimezone=UTC
    username: sale
    password: afcjdnei&78a7&CHddjnacg7D
    # root ncd7&3nkcda8*Cndjnacg7D
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss