spring:
  datasource:
    url: jdbc:postgresql://123.57.241.113:5432/postgres
    username: postgres
    password: afcjdnei&78a7&CHddjnacg7D
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      host: 123.57.241.113
      port: 6379
      password: kdCen83291
      database: 1